import Link from "next/link";
import { currentContext } from "@/lib/auth";
import { query } from "@/lib/db";
import { euro } from "@/lib/format";
import { FinancialChart } from "@/components/financial-chart";
import styles from "./reports.module.css";
function periodStart(period:string){const now=new Date(),start=new Date(now);if(period==="7d")start.setDate(now.getDate()-6);else if(period==="year")start.setMonth(0,1);else start.setDate(now.getDate()-29);start.setHours(0,0,0,0);return start;}
function chartPoints(rows:any[],period:string,start:Date){if(period==="year")return Array.from({length:12},(_,i)=>{const d=new Date(start.getFullYear(),i,1),key=`${d.getFullYear()}-${String(i+1).padStart(2,"0")}`,r=rows.find(x=>String(x.date).slice(0,7)===key);return{label:d.toLocaleDateString("fr-FR",{month:"short"}),income:Number(r?.income||0),expenses:Number(r?.expenses||0)}});const days=period==="7d"?7:30;return Array.from({length:days},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);const key=d.toISOString().slice(0,10),r=rows.find(x=>String(x.date).slice(0,10)===key);return{label:d.toLocaleDateString("fr-FR",{day:"2-digit",month:"short"}),income:Number(r?.income||0),expenses:Number(r?.expenses||0)}});}
export default async function ReportsPage({searchParams}:{searchParams:Promise<{period?:string}>}){const member=await currentContext(),params=await searchParams,period=["7d","30d","year"].includes(params.period||"")?params.period!:"30d",start=periodStart(period),group=period==="year"?"month":"day";
 const [financialRows,contacts,documents,automations,runs,transactions]=await Promise.all([
 query<any>(`SELECT TO_CHAR(date_trunc('${group}',date),'YYYY-MM-DD') date,COALESCE(SUM(CASE WHEN type='INCOME' THEN amount_including_tax ELSE 0 END),0) income,COALESCE(SUM(CASE WHEN type='EXPENSE' THEN amount_including_tax ELSE 0 END),0) expenses FROM transactions WHERE company_id=$1 AND date>=$2 GROUP BY 1 ORDER BY 1`,[member.company_id,start.toISOString().slice(0,10)]),
 query<any>(`SELECT status,value,created_at FROM contacts WHERE company_id=$1 AND created_at>=$2`,[member.company_id,start.toISOString()]),
 query<any>(`SELECT document_type,status,total,issue_date FROM sales_documents WHERE company_id=$1 AND issue_date>=$2`,[member.company_id,start.toISOString().slice(0,10)]),
 query<any>(`SELECT id,is_active,last_run_status FROM automations WHERE company_id=$1`,[member.company_id]),
 query<any>(`SELECT status,started_at FROM automation_runs WHERE company_id=$1 AND started_at>=$2`,[member.company_id,start.toISOString()]),
 query<any>(`SELECT type,category,amount_including_tax FROM transactions WHERE company_id=$1 AND date>=$2`,[member.company_id,start.toISOString().slice(0,10)]),]);
 const points=chartPoints(financialRows,period,start),income=points.reduce((s,p)=>s+p.income,0),expenses=points.reduce((s,p)=>s+p.expenses,0),margin=income-expenses,customers=contacts.filter(x=>x.status==="CUSTOMER").length,conversion=contacts.length?Math.round(customers/contacts.length*100):0,invoiceTotal=documents.filter(x=>x.document_type==="INVOICE").reduce((s,x)=>s+Number(x.total),0),paidTotal=documents.filter(x=>x.document_type==="INVOICE"&&x.status==="PAID").reduce((s,x)=>s+Number(x.total),0);
 const categories=Object.entries(transactions.filter(x=>x.type==="EXPENSE").reduce<Record<string,number>>((a,x)=>{const c=x.category||"Autres";a[c]=(a[c]||0)+Number(x.amount_including_tax);return a},{})).sort((a,b)=>b[1]-a[1]);const successRuns=runs.filter(x=>x.status==="SUCCESS").length,rate=runs.length?Math.round(successRuns/runs.length*100):0;
 return <div className={styles.page}><header className={styles.header}><div><h1>Rapports</h1><p>Une lecture claire de votre chiffre d’affaires, vos charges et votre performance.</p></div><nav className={styles.period}>{[["7d","7 jours"],["30d","30 jours"],["year","Année"]].map(([v,l])=><Link className={period===v?styles.active:""} href={`/reports?period=${v}`} key={v}>{l}</Link>)}</nav></header>
 <section className={styles.stats}><article className={styles.stat}><span>Chiffre d’affaires</span><strong>{euro(income)}</strong><em>Sur la période</em></article><article className={styles.stat}><span>Dépenses</span><strong>{euro(expenses)}</strong><em>{categories.length} catégorie(s)</em></article><article className={styles.stat}><span>Résultat net</span><strong>{euro(margin)}</strong><em>{income?Math.round(margin/income*100):0}% du CA</em></article><article className={styles.stat}><span>Factures encaissées</span><strong>{euro(paidTotal)}</strong><em>sur {euro(invoiceTotal)}</em></article></section>
 <article className={styles.card}><header className={styles.cardHeader}><div><h2>Évolution détaillée du chiffre d’affaires</h2><p>La ligne violette représente les revenus, la ligne orange les dépenses. Survolez les points pour afficher les montants.</p></div></header><FinancialChart points={points} height={330}/><div className={styles.periodSummary}>{points.map(p=><div key={p.label}><strong>{p.label}</strong><span>CA {euro(p.income)}</span><small>Charges {euro(p.expenses)}</small></div>)}</div></article>
 <section className={styles.grid}><article className={styles.card}><header className={styles.cardHeader}><div><h2>Répartition des dépenses</h2><p>Principales catégories de coûts.</p></div></header><div className={styles.breakdown}>{categories.slice(0,6).map(([c,a])=><div className={styles.breakdownRow} key={c}><strong>{c}</strong><span>{euro(a)}</span><div className={styles.progress}><i style={{width:`${expenses?Math.round(a/expenses*100):0}%`}}/></div></div>)}{!categories.length&&<span>Aucune dépense enregistrée.</span>}</div></article><article className={styles.card}><header className={styles.cardHeader}><div><h2>Performance commerciale</h2><p>CRM et facturation.</p></div></header><div className={styles.list}><div className={styles.row}><strong>Nouveaux contacts</strong><span>{contacts.length}</span><small>Période</small></div><div className={styles.row}><strong>Nouveaux clients</strong><span>{customers}</span><small>{conversion}% conversion</small></div><div className={styles.row}><strong>Devis créés</strong><span>{documents.filter(x=>x.document_type==="QUOTE").length}</span><small>Documents</small></div><div className={styles.row}><strong>Automatisations réussies</strong><span>{rate}%</span><small>{successRuns}/{runs.length}</small></div></div></article></section></div>;
}
